### ISSUE TITLE
include files

### ISSUE THREAD

**Issue by ghost** [TimyusVegetari/Demiurge#1]
Add header files placed in include directory to build target in CMakeLists.txt. What IDE do you use?

**Comment by TimyusVegetari** [comment]
I use Code::Blocks. I'll do it today, thank you.

**Comment by TimyusVegetari** [comment]
I did it. Could you say me if it's ok for you ?

**Comment by ghost** [comment]
Sorry it's my bad. There is an issue in QTCreator. I got a problem like this http://stackoverflow.com/questions/25233802/how-do-ides-get-the-project-file-list-from-cmake-cmakelist-txt-and-why-are-llv

**Comment by ghost** [comment]
Yes. That's it. Now I can see all project files. The first issue can be closed.
